# Generated by Django 5.0.6 on 2024-06-24 00:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.IntegerField()),
                ('descripcion', models.CharField(max_length=99)),
                ('imagen', models.ImageField(upload_to='productos')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('rut', models.CharField(max_length=12, primary_key=True, serialize=False, unique=True, verbose_name='RUT')),
                ('nombre', models.CharField(max_length=150, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=150, verbose_name='apellido')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('telefono', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', message="Número de teléfono debe tener el formato: '+999999999'.")], verbose_name='teléfono')),
                ('fecha_nacimiento', models.DateField(verbose_name='fecha de nacimiento')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
