# Generated by Django 5.0.6 on 2024-06-25 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicacion', '0002_usuario_groups_usuario_is_active_usuario_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('destilado', 'Destilado'), ('licor', 'Licor'), ('cerveza', 'Cerveza'), ('whisky', 'Whisky'), ('vinos', 'Vinos'), ('espumantes', 'Espumantes')], default='destilado', max_length=20),
        ),
    ]
